---
language: python
jobs:
  include:
    - env: [ ACTION=install, PYTHONPATH=_install/lib/python2.7/site-packages/ ]
      python: 2.7
      script:
        - mkdir -p "$PYTHONPATH"
        - python setup.py install --prefix=_install
    - env: [ ACTION=test ]
      python: 2.7
      before_install: pip install coverage
      script: nosetests --with-doc --exe --with-coverage
      after_success: bash <(curl -s https://codecov.io/bash)
    - env: [ ACTION=omnilint ]
      language: generic
      install: docker pull lpenz/omnilint
      script: docker run --rm -v "$PWD:$PWD" -e "RWD=$PWD" -e "MY_UID=$UID" lpenz/omnilint
