language: python
python:
  #- "2.6"
  - "2.7"
  #- "3.2"
  #- "3.3"
  #- "3.4"
  #- "nightly"
before_install:
  # coveralls:
  - pip install coveralls
  - SITEPACKAGES=$(pip --version | sed -n 's@.*from \([^ ]\+\) .*@\1@p')
  - echo 'import coverage; coverage.process_startup()' > $SITEPACKAGES/sitecustomize.py
  - printf '[run]\nparallel=True\n' > ~/coverage.cfg
  # static checkers:
  - pip install pyflakes py3kwarn
script:
  # Test if we .gitignore test files:
  - TMP=$(tempfile)
  - git ls-files . --exclude-standard --others | tee "$TMP"
  - if test -s "$TMP"; then false; else true; fi
  # Test if we .gitignore any tracked files:
  - git ls-files -i --exclude-standard | tee "$TMP"
  - if test -s "$TMP"; then false; else true; fi
  # static checkers:
  - pyflakes .
  - if [ "$TRAVIS_PYTHON_VERSION" = "2.7" ]; then py3kwarn .; fi
after_success:
  - find . -name '.coverage*' -exec mv -t . {} +
  - coverage combine
  - coveralls
