language: python
python:
  - "2.7"
  # - "3.2" # mechanize issues
  # - "3.3" # mechanize issues
  # - "3.4" # mechanize issues
  # - "nightly" # mechanize issues
sudo: required
services:
  - docker
before_install:
  # coveralls:
  - pip install coveralls
  # static checkers:
  - pip install py3kwarn
  # omnilint
  - docker pull lpenz/omnilint
script:
  - nosetests --with-doc --exe --with-coverage
  - pip install .
  # Test if we .gitignore test files:
  - TMP=$(tempfile)
  - git ls-files . --exclude-standard --others | tee "$TMP"
  - if test -s "$TMP"; then false; else true; fi
  # Test if we .gitignore any tracked files:
  - git ls-files -i --exclude-standard | tee "$TMP"
  - if test -s "$TMP"; then false; else true; fi
  # omnilint:
  - if [ "$TRAVIS_PYTHON_VERSION" = "2.7" ]; then py3kwarn .; fi
  - if [ "$TRAVIS_PYTHON_VERSION" = "2.7" ]; then docker run --rm -v "$PWD:$PWD" -e "RWD=$PWD" -e "MY_UID=$UID" lpenz/omnilint; fi
after_success:
  - coveralls
